"""update_models_for_s3_and_ai

Revision ID: 321571a73a14
Revises: e333a414f4bf
Create Date: 2026-06-12 16:50:33.508947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321571a73a14'
down_revision = 'e333a414f4bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_referral_rejected_by', 'users', ['rejected_by'], ['id'])
        batch_op.create_foreign_key('fk_referral_completed_by', 'users', ['completed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_referral_completed_by', type_='foreignkey')
        batch_op.drop_constraint('fk_referral_rejected_by', type_='foreignkey')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('completed_by')

    # ### end Alembic commands ###
