"""add_performance_score_to_facilities

Revision ID: 4d006d9ebe55
Revises: 7fec6bdb142d
Create Date: 2026-06-21 05:33:28.302846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d006d9ebe55'
down_revision = '7fec6bdb142d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_action')
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('email_verification_tokens_token_key', type_='unique')

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance_score', sa.Float(), nullable=True))
        batch_op.drop_constraint('facilities_facility_code_key', type_='unique')

    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.alter_column('delivery_method',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'websocket'::character varying"))
        batch_op.alter_column('delivery_status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.drop_index('ix_notification_deliveries_notification_id')
        batch_op.drop_index('ix_notification_deliveries_user_id')
        batch_op.create_index(batch_op.f('ix_notification_deliveries_id'), ['id'], unique=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('password_reset_tokens_token_key', type_='unique')

    with op.batch_alter_table('patient_identifiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mrn', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_patient_identifiers_mrn'), ['mrn'], unique=False)
        batch_op.create_unique_constraint('unique_facility_mrn', ['facility_id', 'mrn'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('refresh_tokens_token_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('refresh_tokens_token_key', ['token'])

    with op.batch_alter_table('patient_identifiers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_facility_mrn', type_='unique')
        batch_op.drop_index(batch_op.f('ix_patient_identifiers_mrn'))
        batch_op.drop_column('mrn')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('password_reset_tokens_token_key', ['token'])

    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_id'))
        batch_op.create_index('ix_notification_deliveries_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notification_deliveries_notification_id', ['notification_id'], unique=False)
        batch_op.alter_column('delivery_status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('delivery_method',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'websocket'::character varying"))

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_unique_constraint('facilities_facility_code_key', ['facility_code'])
        batch_op.drop_column('performance_score')

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('email_verification_tokens_token_key', ['token'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)

    # ### end Alembic commands ###
