"""create_v2_multivariate_deduplication_tables

Revision ID: 7fec6bdb142d
Revises: 321571a73a14
Create Date: 2026-06-20 16:41:42.784612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fec6bdb142d'
down_revision = '321571a73a14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_documents', schema=None) as batch_op:
        # Added postgresql_using to explicitly cast VARCHAR text values to Boolean
        batch_op.alter_column('ai_processed',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="ai_processed::boolean")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_documents', schema=None) as batch_op:
        # Added postgresql_using to cleanly cast Boolean states back to VARCHAR strings
        batch_op.alter_column('ai_processed',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               postgresql_using="ai_processed::text")

    # ### end Alembic commands ###