"""add performance_score to facilities

Revision ID: cd2efc2675fa
Revises: 4d006d9ebe55
Create Date: 2026-06-21 06:39:21.316279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2efc2675fa'
down_revision = '4d006d9ebe55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
