"""add gender column to users

Revision ID: e333a414f4bf
Revises: e82e08802842
Create Date: 2026-06-04 06:30:40.593887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e333a414f4bf'
down_revision = 'e82e08802842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_audit_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notifications_facility_id', 'facilities', ['facility_id'], ['id'])

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_referrals_accepted_by', 'users', ['accepted_by'], ['id'])
    batch_op.create_foreign_key('fk_referrals_rejected_by', 'users', ['rejected_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_referral_accepted_by', type_='foreignkey')
        batch_op.drop_constraint('fk_referral_rejected_by', type_='foreignkey')
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('accepted_by')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
