"""add_gender_to_users

Revision ID: e5227f67358c
Revises: e82e08802842
Create Date: 2026-06-03 03:10:08.003665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5227f67358c'
down_revision = 'e82e08802842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        # FIXED: Provided a name 'fk_notifications_facility_id' for the foreign key
        batch_op.create_foreign_key('fk_notifications_facility_id', 'facilities', ['facility_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        # FIXED: Provided the name 'fk_notifications_facility_id' to drop the constraint
        batch_op.drop_constraint('fk_notifications_facility_id', type_='foreignkey')
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
