"""fix referral schema and add missing fields

Revision ID: e82e08802842
Revises: 012_add_identifier_type
Create Date: 2026-05-28 03:58:08.249400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e82e08802842'
down_revision = '012_add_identifier_type'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('_alembic_tmp_facilities', if_exists=True)
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_facilities_id'), ['id'], unique=False)

    with op.batch_alter_table('facility_counters', schema=None) as batch_op:
        batch_op.drop_index('ix_facility_counters_facility_id')

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    notif_deliv_cols = [c['name'] for c in inspector.get_columns('notification_deliveries')]
    if 'read_at' not in notif_deliv_cols:
        with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
            batch_op.add_column(sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('delivery_method',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'websocket'"))
        batch_op.alter_column('delivery_status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_index('ix_notification_deliveries_notification_id')
        batch_op.drop_index('ix_notification_deliveries_user_id')
        batch_op.create_index(batch_op.f('ix_notification_deliveries_id'), ['id'], unique=False)

    notif_pref_cols = [c['name'] for c in inspector.get_columns('notification_preferences')]
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        if 'enabled' in notif_pref_cols:
            batch_op.alter_column('enabled',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text("'1'"))
        else:
            batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True, server_default=sa.text('true')))

        if 'delivery_methods' in notif_pref_cols:
            batch_op.alter_column('delivery_methods',
                   existing_type=sqlite.JSON(),
                   nullable=True,
                   existing_server_default=sa.text('\'["websocket"]\''))
        else:
            batch_op.add_column(sa.Column('delivery_methods', sqlite.JSON(), nullable=True))

        pref_indexes = [i['name'] for i in inspector.get_indexes('notification_preferences')]
        if 'ix_notification_preferences_user_id' in pref_indexes:
            batch_op.drop_index('ix_notification_preferences_user_id')
        batch_op.create_index(batch_op.f('ix_notification_preferences_id'), ['id'], unique=False)

    if 'notification_queue' in inspector.get_table_names():
        with op.batch_alter_table('notification_queue', schema=None) as batch_op:
            batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True,
                   existing_server_default=sa.text("'pending'"))
            batch_op.alter_column('attempts',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   existing_server_default=sa.text("'0'"))
            batch_op.create_index(batch_op.f('ix_notification_queue_id'), ['id'], unique=False)
            # Only drop if they actually exist
            queue_indexes = [i['name'] for i in inspector.get_indexes('notification_queue')]
            if 'ix_notification_queue_notification_id' in queue_indexes:
                batch_op.drop_index('ix_notification_queue_notification_id')
            if 'ix_notification_queue_user_id' in queue_indexes:
                batch_op.drop_index('ix_notification_queue_user_id')

    if 'notification_templates' in inspector.get_table_names():
        with op.batch_alter_table('notification_templates', schema=None) as batch_op:
            batch_op.alter_column('default_roles',
                   existing_type=sqlite.JSON(),
                   nullable=True,
                   existing_server_default=sa.text("'[]'"))
            batch_op.alter_column('backend_source',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True,
                   existing_server_default=sa.text("'system'"))
            batch_op.alter_column('is_active',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('(true)'))
            batch_op.create_index(batch_op.f('ix_notification_templates_id'), ['id'], unique=False)

    if 'notifications' in inspector.get_table_names():
        with op.batch_alter_table('notifications', schema=None) as batch_op:
            batch_op.alter_column('details',
                   existing_type=sqlite.JSON(),
                   nullable=True,
                   existing_server_default=sa.text("'{}'"))
            batch_op.alter_column('actions',
                   existing_type=sqlite.JSON(),
                   nullable=True,
                   existing_server_default=sa.text("'[]'"))
            batch_op.alter_column('roles',
                   existing_type=sqlite.JSON(),
                   nullable=True,
                   existing_server_default=sa.text("'[]'"))
            batch_op.alter_column('backend_source',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True,
                   existing_server_default=sa.text("'system'"))
            batch_op.alter_column('is_read',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text("'0'"))
            batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
            notif_indexes = [i['name'] for i in inspector.get_indexes('notifications')]
            if 'ix_notifications_notification_type' in notif_indexes:
                batch_op.drop_index('ix_notifications_notification_type')
            if 'ix_notifications_user_id' in notif_indexes:
                batch_op.drop_index('ix_notifications_user_id')

    with op.batch_alter_table('patient_identifiers', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_identifiers_facility_id')
        batch_op.drop_index('ix_patient_identifiers_patient_id')
        batch_op.create_index(batch_op.f('ix_patient_identifiers_id'), ['id'], unique=False)
        batch_op.create_unique_constraint('unique_facility_mrn', ['facility_id', 'mrn'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index('ix_patients_facility_id')
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)

    with op.batch_alter_table('referral_documents', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index('ix_referral_documents_referral_id')
        batch_op.create_index(batch_op.f('ix_referral_documents_id'), ['id'], unique=False)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('reason_for_referral',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index('ix_referrals_from_facility_id')
        batch_op.drop_index('ix_referrals_patient_id')
        batch_op.drop_index('ix_referrals_status')
        batch_op.drop_index('ix_referrals_to_facility_id')
        batch_op.create_index(batch_op.f('ix_referrals_id'), ['id'], unique=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)

    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.create_index(batch_op.f('ix_system_metrics_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_facility_id')
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_user_facility', 'facilities', ['facility_id'], ['id'])

    with op.batch_alter_table('voice_notes', schema=None) as batch_op:
        batch_op.alter_column('audio_file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_voice_notes_referral_id')
        batch_op.create_index(batch_op.f('ix_voice_notes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_notes_id'))
        batch_op.create_index('ix_voice_notes_referral_id', ['referral_id'], unique=False)
        batch_op.alter_column('audio_file_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_facility', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.create_index('ix_users_facility_id', ['facility_id'], unique=False)

    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_metrics_id'))
        batch_op.alter_column('details',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_id'))
        batch_op.create_index('ix_referrals_to_facility_id', ['to_facility_id'], unique=False)
        batch_op.create_index('ix_referrals_status', ['status'], unique=False)
        batch_op.create_index('ix_referrals_patient_id', ['patient_id'], unique=False)
        batch_op.create_index('ix_referrals_from_facility_id', ['from_facility_id'], unique=False)
        batch_op.alter_column('reason_for_referral',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('referral_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_documents_id'))
        batch_op.create_index('ix_referral_documents_referral_id', ['referral_id'], unique=False)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_id'))
        batch_op.create_index('ix_patients_facility_id', ['facility_id'], unique=False)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('patient_identifiers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_facility_mrn', type_='unique')
        batch_op.drop_index(batch_op.f('ix_patient_identifiers_id'))
        batch_op.create_index('ix_patient_identifiers_patient_id', ['patient_id'], unique=False)
        batch_op.create_index('ix_patient_identifiers_facility_id', ['facility_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_notification_type', ['notification_type'], unique=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('backend_source',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'system'"))
        batch_op.alter_column('roles',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('actions',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('details',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_templates_id'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('backend_source',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'system'"))
        batch_op.alter_column('default_roles',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_queue_id'))
        batch_op.create_index('ix_notification_queue_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notification_queue_notification_id', ['notification_id'], unique=False)
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_id'))
        batch_op.create_index('ix_notification_preferences_user_id', ['user_id'], unique=False)
        batch_op.alter_column('delivery_methods',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text('\'["websocket"]\''))
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_id'))
        batch_op.create_index('ix_notification_deliveries_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notification_deliveries_notification_id', ['notification_id'], unique=False)
        batch_op.alter_column('delivery_status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('delivery_method',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'websocket'"))
        batch_op.drop_column('read_at')

    with op.batch_alter_table('facility_counters', schema=None) as batch_op:
        batch_op.create_index('ix_facility_counters_facility_id', ['facility_id'], unique=False)

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_id'))
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    op.create_table('_alembic_tmp_facilities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('facility_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('level', sa.VARCHAR(length=50), nullable=False),
    sa.Column('county', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('performance_score', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_code')
    )
    # ### end Alembic commands ###


